"use client";

import ReactMarkdown from "react-markdown";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Download, RefreshCw, AlertCircle, FileDown } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { ScrollArea } from "@/components/ui/scroll-area";

interface PrdEditorProps {
  content: string;
  isRoast?: boolean;
  onReset: () => void;
}

export function PrdEditor({ content, isRoast = false, onReset }: PrdEditorProps) {
  const handleExportMd = () => {
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = isRoast ? "roast-result.md" : "saas-prd.md";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleExportPdf = async () => {
    const { jsPDF } = await import("jspdf");

    const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const M = { top: 25, bottom: 20, left: 22, right: 22 };
    const W = pageWidth - M.left - M.right; // usable content width
    const LH = 5; // standard line height for body text
    let y = M.top;
    let pageNum = 1;

    type RGB = [number, number, number];
    const C = {
      text:     [30, 41, 59]    as RGB,
      h1:       [15, 23, 42]    as RGB,
      h2:       [30, 41, 59]    as RGB,
      h3:       [51, 65, 85]    as RGB,
      muted:    [100, 116, 139] as RGB,
      accent:   [59, 130, 246]  as RGB,
      rule:     [226, 232, 240] as RGB,
      codeBg:   [241, 245, 249] as RGB,
      quoteBg:  [248, 250, 252] as RGB,
    };

    // ── Strip markdown inline formatting ──
    const strip = (s: string) =>
      s.replace(/\*\*(.*?)\*\*/g, "$1")
       .replace(/\*(.*?)\*/g, "$1")
       .replace(/`([^`]+)`/g, "$1");

    // ── Footer ──
    const footer = () => {
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...C.muted);
      doc.setDrawColor(...C.rule);
      doc.setLineWidth(0.3);
      doc.line(M.left, pageHeight - 15, pageWidth - M.right, pageHeight - 15);
      doc.text("Generated by PRD Maker", M.left, pageHeight - 10);
      doc.text(`Page ${pageNum}`, pageWidth / 2, pageHeight - 10, { align: "center" });
      doc.text(
        new Date().toLocaleDateString("id-ID", { year: "numeric", month: "long", day: "numeric" }),
        pageWidth - M.right, pageHeight - 10, { align: "right" }
      );
    };

    // ── New page if needed ──
    const newPageIf = (need: number) => {
      if (y + need > pageHeight - M.bottom - 6) {
        footer();
        doc.addPage();
        pageNum++;
        y = M.top;
      }
    };

    // ── Print wrapped text — the ONLY function that writes body text ──
    // Returns the number of mm advanced.
    const printText = (
      text: string, x: number, maxW: number,
      size: number, style: string, lh: number
    ): number => {
      doc.setFontSize(size);
      doc.setFont("helvetica", style);
      const clean = strip(text);
      const wrapped: string[] = doc.splitTextToSize(clean, maxW);
      let advanced = 0;
      for (const wl of wrapped) {
        newPageIf(lh);
        doc.text(wl, x, y);
        y += lh;
        advanced += lh;
      }
      return advanced;
    };

    // ── Detect leading whitespace indent ──
    const indentOf = (raw: string): number => {
      const m = raw.match(/^(\s*)/);
      return m ? Math.floor(m[1].length / 2) : 0;
    };

    // ── Main loop ──
    const lines = content.split("\n");
    let inCode = false;

    for (let i = 0; i < lines.length; i++) {
      const raw = lines[i];
      const t = raw.trim();

      // Code fence toggle
      if (t.startsWith("```")) {
        inCode = !inCode;
        y += 2;
        continue;
      }

      // Inside code block
      if (inCode) {
        newPageIf(5.5);
        doc.setFillColor(...C.codeBg);
        doc.rect(M.left, y - 3.5, W, 5.5, "F");
        doc.setFontSize(8);
        doc.setFont("courier", "normal");
        doc.setTextColor(...C.text);
        const codeLine = raw.length > 100 ? raw.substring(0, 97) + "..." : raw;
        doc.text(codeLine || " ", M.left + 3, y);
        y += 5.5;
        continue;
      }

      // Blank line
      if (t === "") { y += 3; continue; }

      // Horizontal rule
      if (/^[-*_]{3,}$/.test(t)) {
        newPageIf(10);
        y += 4;
        doc.setDrawColor(...C.rule);
        doc.setLineWidth(0.4);
        doc.line(M.left, y, pageWidth - M.right, y);
        y += 6;
        continue;
      }

      // ── H1 ──
      if (/^# [^#]/.test(t)) {
        newPageIf(20);
        y += 10;
        doc.setTextColor(...C.h1);
        printText(t.replace(/^#\s*/, ""), M.left, W, 20, "bold", 8);
        doc.setDrawColor(...C.accent);
        doc.setLineWidth(0.8);
        doc.line(M.left, y + 1, M.left + 40, y + 1);
        y += 5;
        doc.setTextColor(...C.text);
        continue;
      }

      // ── H2 ──
      if (/^## [^#]/.test(t)) {
        newPageIf(16);
        y += 8;
        doc.setTextColor(...C.h2);
        printText(t.replace(/^##\s*/, ""), M.left, W, 15, "bold", 6.5);
        doc.setDrawColor(...C.rule);
        doc.setLineWidth(0.3);
        doc.line(M.left, y + 1, pageWidth - M.right, y + 1);
        y += 4;
        doc.setTextColor(...C.text);
        continue;
      }

      // ── H3 ──
      if (/^### [^#]/.test(t)) {
        newPageIf(14);
        y += 6;
        doc.setTextColor(...C.h3);
        printText(t.replace(/^###\s*/, ""), M.left, W, 13, "bold", 5.5);
        y += 3;
        doc.setTextColor(...C.text);
        continue;
      }

      // ── H4 ──
      if (/^#### /.test(t)) {
        newPageIf(12);
        y += 5;
        doc.setTextColor(...C.h3);
        printText(t.replace(/^####\s*/, ""), M.left + 2, W - 2, 11, "bold", 5);
        y += 2;
        doc.setTextColor(...C.text);
        continue;
      }

      // ── Blockquote ──
      if (t.startsWith("> ")) {
        const qt = strip(t.replace(/^>\s*/, ""));
        doc.setFontSize(10);
        const wrapped: string[] = doc.splitTextToSize(qt, W - 14);
        const bh = wrapped.length * LH + 6;
        newPageIf(bh);
        doc.setFillColor(...C.quoteBg);
        doc.roundedRect(M.left, y - 1, W, bh, 1.5, 1.5, "F");
        doc.setFillColor(...C.accent);
        doc.rect(M.left, y - 1, 1.2, bh, "F");
        doc.setTextColor(...C.h3);
        doc.setFont("helvetica", "italic");
        y += 2;
        for (const wl of wrapped) {
          doc.text(wl, M.left + 6, y);
          y += LH;
        }
        y += 3;
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...C.text);
        continue;
      }

      // ── Bullet list (with nesting) ──
      if (/^\s*[-*]\s/.test(raw)) {
        const lvl = indentOf(raw);
        const off = lvl * 5;
        const bx = M.left + 2 + off;
        const tx = bx + 4;
        const aw = W - off - 6;
        const bullet = ["•", "◦", "–"][Math.min(lvl, 2)];

        const bodyText = strip(t.replace(/^[-*]\s*/, ""));
        doc.setFontSize(10);
        const wrapped: string[] = doc.splitTextToSize(bodyText, aw);
        const needed = wrapped.length * LH;
        newPageIf(needed);

        doc.setFont("helvetica", "normal");
        doc.setTextColor(...C.text);
        doc.text(bullet, bx, y);
        for (const wl of wrapped) {
          doc.text(wl, tx, y);
          y += LH;
        }
        continue;
      }

      // ── Numbered list (with nesting) ──
      if (/^\s*\d+\.\s/.test(raw)) {
        const lvl = indentOf(raw);
        const off = lvl * 5;
        const nx = M.left + 2 + off;
        const tx = nx + 7;
        const aw = W - off - 9;

        const m = t.match(/^(\d+\.)\s*(.*)/);
        if (m) {
          const bodyText = strip(m[2]);
          doc.setFontSize(10);
          const wrapped: string[] = doc.splitTextToSize(bodyText, aw);
          const needed = wrapped.length * LH;
          newPageIf(needed);

          doc.setTextColor(...C.text);
          doc.setFont("helvetica", "bold");
          doc.text(m[1], nx, y);
          doc.setFont("helvetica", "normal");
          for (const wl of wrapped) {
            doc.text(wl, tx, y);
            y += LH;
          }
        }
        continue;
      }

      // ── Regular paragraph ──
      doc.setTextColor(...C.text);
      const bodyText = strip(t);
      doc.setFontSize(10);
      const wrapped: string[] = doc.splitTextToSize(bodyText, W);
      const needed = wrapped.length * LH;
      newPageIf(needed);
      doc.setFont("helvetica", "normal");
      for (const wl of wrapped) {
        doc.text(wl, M.left, y);
        y += LH;
      }
    }

    footer();
    doc.save(isRoast ? "roast-result.pdf" : "saas-prd.pdf");
  };

  const handleSaveToHistory = () => {
    if (isRoast) return;
    const history = JSON.parse(localStorage.getItem("prd_history") || "[]");
    history.push({
      id: Date.now().toString(),
      date: new Date().toISOString(),
      content: content,
    });
    localStorage.setItem("prd_history", JSON.stringify(history));
    alert("Berhasil disimpan di Local Storage browser!");
  };

  return (
    <Card className="w-full max-w-4xl mx-auto shadow-xl border-border/50 bg-background/50 backdrop-blur-sm">
      <CardHeader className="flex flex-row items-center justify-between border-b border-border/50 pb-4">
        <div>
          <CardTitle className="text-2xl font-bold bg-gradient-to-r from-blue-600 to-indigo-500 bg-clip-text text-transparent">
            {isRoast ? "Roast Result" : "Generated PRD"}
          </CardTitle>
          <CardDescription>
            {isRoast 
              ? "Feedback brutal untuk ide SaaS Anda." 
              : "Product Requirements Document siap pakai."}
          </CardDescription>
        </div>
        <div className="flex flex-wrap justify-end gap-2">
          {!isRoast && content && (
            <Button variant="outline" onClick={handleSaveToHistory} title="Simpan di Browser">
              Simpan
            </Button>
          )}
          <Button variant="outline" onClick={handleExportMd}>
            <Download className="w-4 h-4 mr-2" />
            Export .md
          </Button>
          <Button variant="outline" onClick={handleExportPdf}>
            <FileDown className="w-4 h-4 mr-2" />
            Export PDF
          </Button>
          <Button onClick={onReset} variant={isRoast ? "default" : "secondary"}>
            <RefreshCw className="w-4 h-4 mr-2" />
            {isRoast ? "Revisi Ide" : "Buat Baru"}
          </Button>
        </div>
      </CardHeader>
      
      <CardContent className="p-0">
        {isRoast && (
           <Alert variant="destructive" className="m-6 mb-0">
             <AlertCircle className="h-4 w-4" />
             <AlertTitle>Warning!</AlertTitle>
             <AlertDescription>
               Ini adalah mode Roast. Feedback di bawah mungkin terasa pedas, tapi ini untuk memastikan ide Anda benar-benar valid sebelum membuang waktu dan biaya.
             </AlertDescription>
           </Alert>
        )}
        
        <ScrollArea className="h-[600px] w-full p-6">
          <div id="prd-content-export" className="prose prose-slate dark:prose-invert max-w-none prose-headings:font-bold prose-h1:text-3xl prose-a:text-blue-600">
            {content ? (
              <ReactMarkdown>{content}</ReactMarkdown>
            ) : (
              <div className="flex items-center justify-center h-full text-muted-foreground animate-pulse">
                Generating content...
              </div>
            )}
          </div>
        </ScrollArea>
      </CardContent>
    </Card>
  );
}
